version: '3.8'

networks: 
    fudge-net:
        driver: bridge

services:
    mosquitto:
        image: eclipse-mosquitto:2.0.10
        container_name: broker
        ports:
            - 1883:1883
        volumes:
            - ./config/mosquitto.conf:/mosquitto/config/mosquitto.conf
            - ./config/mosquitto.pwd:/mosquitto/config/mosquitto.pwd
        networks: 
            - fudge-net

    influxdb:
        image: influxdb:1.8
        container_name: pmod
        ports:
            - 8086:8086
        environment:
            INFLUXDB_DB: "fudgedb"
            INFLUXDB_ADMIN_ENABLED: "true"
            INFLUXDB_ADMIN_USER: "fudger"
            INFLUXDB_ADMIN_PASSWORD: "uforobot"
        volumes:
            - ./data/:/var/lib/influxdb
        networks: 
            - fudge-net

    grafana:
        image: grafana/grafana:7.5.7
        container_name: grafana
        ports: 
            - 3000:3000
        environment:
            GF_SECURITY_ADMIN_USER: admin
            GF_SECURITY_ADMIN_PASSWORD: admin
        volumes:
            - ./data/:/var/lib/grafana
        networks: 
            - fudge-net


